import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useDispatch, useSelector } from 'react-redux'
import React, { useEffect } from 'react'
import LoginPage from '../components/LoginPage'
import { authActions } from '../store/authReducer'
import LogoutButton from '../components/LogoutButton'

export default function Home() {
  const isAuthenticated = useSelector(state => state.auth.isAuthenticated)
  const user = useSelector(state => state.auth.user)
  const dispatch = useDispatch()

  useEffect(() => {
    const storedUser = JSON.parse(localStorage.getItem('user'))
    const storedAuth = JSON.parse(localStorage.getItem('isAuthenticated'))
    if (storedAuth && storedUser) {
      dispatch(authActions.login())
      dispatch(authActions.setUser(storedUser))
    }
  }, [])
  
  if (!isAuthenticated) {
    return (
      <React.Fragment>
        <LoginPage />
      </React.Fragment>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>hallo, {user.username}</p>
        <LogoutButton />
      </main>

    </div>
  )
}
